# Generated by Django 6.0.4 on 2026-05-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='features',
            field=models.TextField(blank=True, help_text='Enter features separated by new lines'),
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(default='lucide:grid-3x3', help_text='Iconify icon name', max_length=50),
        ),
    ]
