# Generated by Django 6.0.4 on 2026-05-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(default='Bipin Decor', max_length=100)),
                ('footer_description', models.TextField(blank=True, default='Premium interior decoration and home renovation services specializing in UV Marble Sheets, PVC Paneling, and False Ceilings.')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('contact_email', models.EmailField(blank=True, default='info@bipindecor.com', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='+91 9876543210', max_length=20)),
                ('contact_address', models.TextField(blank=True, default='123 Decor Street, City')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('whatsapp_message', models.CharField(blank=True, default='Hi Bipin Decor, I need a consultation.', max_length=200)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('seo_title', models.CharField(blank=True, default='Bipin Interior | Premium Decor Studio', max_length=100)),
                ('seo_description', models.TextField(blank=True)),
                ('seo_keywords', models.TextField(blank=True)),
                ('primary_color', models.CharField(blank=True, default='#C5A059', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
