# Generated by Django 6.0.4 on 2026-05-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='category_section_subtitle',
            field=models.CharField(default='Explore Spaces', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='category_section_title',
            field=models.CharField(default='Design by Category', max_length=200),
        ),
    ]
