# Generated by Django 6.0.4 on 2026-05-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sitesetting_category_section_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='service_section_subtitle',
            field=models.CharField(default='Our Expertise', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='service_section_title',
            field=models.CharField(default='Bipin Decor Services', max_length=200),
        ),
    ]
