# Generated by Django 6.0.4 on 2026-05-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sitesetting_service_section_subtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='lucide:check-circle', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Why Choose Us',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='why_choose_description',
            field=models.TextField(blank=True, default="We don't just renovate spaces; we craft environments that reflect your personal style while ensuring durability and flawless execution."),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='why_choose_image',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='why_choose_subtitle',
            field=models.CharField(default='Why Choose Us', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='why_choose_title',
            field=models.CharField(default='Craftsmanship Meets Elegance', max_length=200),
        ),
    ]
