# Generated by Django 6.0.4 on 2026-05-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_whychooseus_sitesetting_why_choose_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='lucide:circle', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Our Process Steps',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='why_choose_description',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='why_choose_image',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='why_choose_subtitle',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='why_choose_title',
        ),
    ]
