# Generated by Django 6.0.4 on 2026-05-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_ourprocess_remove_sitesetting_why_choose_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='process_section_description',
            field=models.TextField(blank=True, default='Every project is handled with thoughtful planning, premium craftsmanship, and a seamless execution process.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='process_section_subtitle',
            field=models.CharField(default='Our Process', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='process_section_title',
            field=models.CharField(default='A Refined Journey From Concept to Completion', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='why_choose_description',
            field=models.TextField(blank=True, default="We don't just renovate spaces; we craft environments that reflect your personal style while ensuring durability and flawless execution."),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='why_choose_subtitle',
            field=models.CharField(default='Why Choose Us', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='why_choose_title',
            field=models.CharField(default='Craftsmanship Meets Elegance', max_length=200),
        ),
    ]
