# Generated by Django 6.0.4 on 2026-05-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sitesetting_process_section_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='why_choose_image',
            field=models.ImageField(blank=True, null=True, upload_to='why_choose/'),
        ),
    ]
