# Generated by Django 6.0.4 on 2026-05-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sitesetting_why_choose_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(default='Client', max_length=100)),
                ('photo_url', models.URLField(blank=True, default='')),
                ('rating', models.IntegerField(default=5)),
                ('review', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='testimonial_section_subtitle',
            field=models.CharField(default='CLIENT STORIES', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='testimonial_section_title',
            field=models.CharField(default='Words of Trust', max_length=200),
        ),
    ]
