# Generated by Django 6.0.4 on 2026-05-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_testimonial_sitesetting_testimonial_section_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='cta_background_image',
            field=models.ImageField(blank=True, null=True, upload_to='cta/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='cta_button_text',
            field=models.CharField(default='Schedule Consultation', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='cta_description',
            field=models.TextField(blank=True, default='Book a consultation with our experts today and take the first step towards your dream Decor.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='cta_title',
            field=models.CharField(default='Ready to Transform Your Space?', max_length=200),
        ),
    ]
