# Generated by Django 6.0.4 on 2026-05-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_sitesetting_cta_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='hero_background_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_description',
            field=models.TextField(blank=True, default='Crafted with precision, designed with elegance — we transform everyday spaces into timeless Decors.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_subtitle',
            field=models.CharField(default='Bipin Decor Studio', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_title',
            field=models.CharField(default='Elevate Your Living Space', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_video',
            field=models.FileField(blank=True, null=True, upload_to='hero/'),
        ),
    ]
