# Generated by Django 6.0.4 on 2026-05-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_sitesetting_hero_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='about_card1_desc',
            field=models.TextField(blank=True, default='We meticulously source the highest grade UV marble, PVC panels, and WPC louvers. Our materials are chosen for their durability, finish, and ability to elevate any space.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_card1_icon',
            field=models.CharField(default='lucide:gem', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_card1_title',
            field=models.CharField(default='Premium Materials', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_card2_desc',
            field=models.TextField(blank=True, default='Luxury is in the details. Our installation process is marked by exact measurements, seamless joints, and a flawless finish that defines high-end Decor design.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_card2_icon',
            field=models.CharField(default='lucide:ruler', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_card2_title',
            field=models.CharField(default='Precision Execution', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_card3_desc',
            field=models.TextField(blank=True, default='We collaborate closely with our clients, ensuring their vision is translated into reality with transparency, timely delivery, and utmost professionalism.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_card3_icon',
            field=models.CharField(default='lucide:users', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_card3_title',
            field=models.CharField(default='Client-Centric Approach', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_expertise_image1',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_expertise_image2',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_expertise_p1',
            field=models.TextField(blank=True, default='Behind every flawless installation is a team of dedicated artisans. Our installers are not just workers; they are craftsmen who take immense pride in their art.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_expertise_p2',
            field=models.TextField(blank=True, default='With rigorous training and years of hands-on experience, our team handles complex architectural challenges with ease, ensuring that every panel, sheet, and louver is placed with absolute perfection.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_expertise_subtitle',
            field=models.CharField(default='Our Expertise', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_expertise_title',
            field=models.CharField(default='Master Artisans at Work', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_hero_description',
            field=models.TextField(blank=True, default='Crafting luxurious, functional, and timeless spaces with uncompromising attention to detail.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_hero_subtitle',
            field=models.CharField(default='Our Story', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_hero_title',
            field=models.CharField(default='About Bipin Decors', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_philosophy_subtitle',
            field=models.CharField(default='Our Philosophy', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_philosophy_title',
            field=models.CharField(default='Uncompromising Craftsmanship', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_story_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_story_p1',
            field=models.TextField(blank=True, default='Founded with a passion for transforming ordinary rooms into extraordinary environments, Bipin Decors has grown into a premier Decor installation studio. We specialize in bringing high-end residential and commercial visions to life.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_story_p2',
            field=models.TextField(blank=True, default='Our journey began over a decade ago with a simple philosophy: Decor design should not only look stunning but also withstand the test of time. Today, we are known for our meticulous craftsmanship in UV marble sheets, PVC paneling, and bespoke false ceilings.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_story_projects',
            field=models.CharField(default='500+', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_story_subtitle',
            field=models.CharField(default='The Beginning', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_story_title',
            field=models.CharField(default='A Legacy of Design Excellence', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_story_years',
            field=models.CharField(default='10+', max_length=20),
        ),
    ]
