# Generated by Django 6.0.4 on 2026-05-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_sitesetting_about_card1_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='contact_card_badge',
            field=models.CharField(default='Direct Support', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_card_p1',
            field=models.TextField(blank=True, default='Feel free to contact us for false ceiling, PVC paneling, renovation, or interior decoration work.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_card_p2',
            field=models.TextField(blank=True, default='No bots, no delay — direct interaction with our team.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_card_title',
            field=models.CharField(default='Talk to Us Directly 😊', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_hero_description',
            field=models.TextField(blank=True, default='Whether you have a clear vision or need expert guidance, our team is here to bring your ideas to life.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='contact/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_hero_subtitle',
            field=models.CharField(default='Get in Touch', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_hero_title',
            field=models.CharField(default="Let's Discuss Your Project", max_length=200),
        ),
    ]
