# Generated by Django 6.0.4 on 2026-05-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_sitesetting_contact_card_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='service_hero_description',
            field=models.TextField(blank=True, default='Discover our range of premium Decor services, from precision false ceilings to elegant wall paneling.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='service_hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='services_hero/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='service_hero_subtitle',
            field=models.CharField(default='What We Do', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='service_hero_title',
            field=models.CharField(default='Expert Solutions for Modern Living', max_length=200),
        ),
    ]
