# Generated by Django 6.0.4 on 2026-05-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_sitesetting_service_hero_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='portfolio_hero_description',
            field=models.TextField(blank=True, default='Explore our curated portfolio of stunning transformations and bespoke installations.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='portfolio_hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_hero/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='portfolio_hero_subtitle',
            field=models.CharField(default='Our Masterpieces', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='portfolio_hero_title',
            field=models.CharField(default='Work Gallery', max_length=200),
        ),
    ]
